### ISSUE TITLE
Multiple component selection with CTRL+LMB or Rubber band selection with either LMB or RMB.

### ISSUE THREAD

**Issue by shujaatak** [Arokip/fdl_demo_app#1]
LMB = Left Mouse Button
RMB = Right Mouse Button

**Comment by Arokip** [comment]
As far as I know it's not currently easy or not even possible to detect RMB click in Flutter. I an not sure about ctrl+mouse.
This is multiplatform app and on mobile devices there is no mouse so the gestures will be adapted for all types of devices.

Multiple selection will be implemented soon in this demo.

**Comment by shujaatak** [comment]
> This is multiplatform app and on mobile devices there is no mouse so the gestures will be adapted for all types of devices.

Very valid reason!

**Comment by shujaatak** [comment]
Although someone who want to support desktop platforms can right platform specific code wherever needed.
